# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'otopac_price' do
  pod 'AppCenter/Crashes', '~> 1.13.2'
  pod 'AppCenter/Analytics', '~> 1.13.2'
  pod 'AppCenterReactNativeShared', '~> 1.12.2'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for otopac_price

  rn_path = '../node_modules/react-native'
  pod 'React', path: rn_path, subspecs: [
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  platform :ios, '9.0'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'react-native-youtube', :path => '../node_modules/react-native-youtube'

  target 'otopac_priceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'otopac_price-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for otopac_price-tvOS

  target 'otopac_price-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


post_install do |installer|
    targets_to_ignore = %w(React yoga)
    installer.pods_project.targets.each do |target|
        if targets_to_ignore.include? target.name
            target.remove_from_project
        end
    end
end
